// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGAfbMpvateK4P6-XyfmM7cTHq4S8cAWA',
    appId: '1:814666322128:web:cdaa6aedb96877ea914ed5',
    messagingSenderId: '814666322128',
    projectId: 'verbat-996e0',
    authDomain: 'verbat-996e0.firebaseapp.com',
    storageBucket: 'verbat-996e0.firebasestorage.app',
    measurementId: 'G-EN5JJPXP8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh1wYOCCuSicYO2m7lXc_942cq-H8AP8g',
    appId: '1:814666322128:android:ccaffdfae0d5bf78914ed5',
    messagingSenderId: '814666322128',
    projectId: 'verbat-996e0',
    storageBucket: 'verbat-996e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ayHsyurDPsLVy_P5uiThFSzozE7AVZQ',
    appId: '1:814666322128:ios:686ad83a8b3338f9914ed5',
    messagingSenderId: '814666322128',
    projectId: 'verbat-996e0',
    storageBucket: 'verbat-996e0.firebasestorage.app',
    iosBundleId: 'com.example.verbatFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0ayHsyurDPsLVy_P5uiThFSzozE7AVZQ',
    appId: '1:814666322128:ios:686ad83a8b3338f9914ed5',
    messagingSenderId: '814666322128',
    projectId: 'verbat-996e0',
    storageBucket: 'verbat-996e0.firebasestorage.app',
    iosBundleId: 'com.example.verbatFinal',
  );
}
